import { iNetworkInfo } from '../interfaces/iNetwork';
import { CHAIN_TYPE } from './ChainType';
import { PROVIDER_TYPES } from './ProviderTypes';

export const networkListInfoProd: iNetworkInfo[] = [
  {
    id: 1,
    isInUse: true,
    name: 'Arbitrum',
    symbol: 'Arbitrum',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '42161',
    rpcUrls: ['https://arbitrum.llamarpc.com'],
    img: 'arbitrum.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    contractAddress: '0xf82447768a94256BBf239B21De5b2e149683CFC4',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '0x69C4d08463F9BD15949d1c7a7cAACBfCa4AF3cD4',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://arbiscan.io/'],
    hasBorrowPool: true,
  },
  {
    id: 2,
    isInUse: true,
    name: 'PolygonZKEVM',
    symbol: 'PolygonZKEVM',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '1101',
    rpcUrls: ['https://rpc.ankr.com/polygon_zkevm'],
    img: 'polygon.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0x1E4a5963aBFD975d8c9021ce480b42188849D41d',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://zkevm.polygonscan.com/'],
    hasBorrowPool: false,
  },
  {
    id: 3,
    isInUse: true,
    name: 'Base',
    symbol: 'Base',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '8453',
    rpcUrls: ['https://base.llamarpc.com'],
    img: 'base.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDC',
        symbol: 'USDC',
        decimals: '6',
        contractAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://basescan.org'],
    hasBorrowPool: false,
  },
  {
    id: 4,
    isInUse: true,
    name: 'Linea',
    symbol: 'Linea',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '59144',
    rpcUrls: ['https://linea.blockpi.network/v1/rpc/public'],
    img: 'linea.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0xA219439258ca9da29E9Cc4cE5596924745e12B93',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://lineascan.build'],
    hasBorrowPool: false,
  },
  {
    id: 5,
    isInUse: true,
    name: 'Gnosis',
    symbol: 'Gnosis',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '100',
    rpcUrls: [
      'https://rpc.gnosischain.com/',
      'https://rpc.xdaichain.com/',
      'https://dai.poa.network/',
    ],
    img: 'gnosis.svg',
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'XDAI',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0x4ECaBa5870353805a9F068101A40E0f32ed605C6',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://gnosisscan.io'],
    hasBorrowPool: false,
  },
  {
    id: 6,
    isInUse: true,
    name: 'CELO',
    symbol: 'CEL',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '42220',
    rpcUrls: ['https://forno.celo.org'],
    img: 'celo.svg',
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0x617f3112bf5397D0467D315cC709EF968D9ba546',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://celoscan.io/'],
    hasBorrowPool: false,
  },
  {
    id: 7,
    isInUse: true,
    name: 'XDC Network',
    symbol: 'XDC',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '50',
    rpcUrls: ['https://rpc.xdcrpc.com'],
    img: 'xdc.svg',
    nativeCurrency: {
      name: 'XDC',
      symbol: 'XDC',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: 'xdc49d3f7543335cf38Fa10889CCFF10207e22110B5',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://xdcscan.io'],
    hasBorrowPool: false,
  },
  {
    id: 8,
    isInUse: true,
    name: 'Mantle',
    symbol: 'Mantle',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '5000',
    rpcUrls: ['https://mantle.publicnode.com'],
    img: 'mantle.svg',
    nativeCurrency: {
      name: 'MNT',
      symbol: 'MNT',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0x201EBa5CC46D216Ce6DC03F6a759e8E766e956aE',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://explorer.mantle.xyz'],
    hasBorrowPool: false,
  },
  {
    id: 9,
    isInUse: true,
    name: 'Scroll',
    symbol: 'Scroll',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '534352',
    rpcUrls: ['https://rpc.scroll.io'],
    img: 'scroll.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    contractAddress: '',
    cryptos: [
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress: '0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df',
        isDefaultStable: true,
      },
      {
        name: 'BCLTT',
        symbol: 'BCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanBorrower: true,
      },
      {
        name: 'LCLTT',
        symbol: 'LCLTT',
        decimals: '6',
        contractAddress: '',
        isDefaultStable: false,
        isLoanCreditor: true,
      },
    ],
    blockExplorerUrls: ['https://scrollscan.com'],
    hasBorrowPool: false,
  },

];
