import { iNetworkInfo } from '../interfaces/iNetwork';
import { CHAIN_TYPE } from './ChainType';
import { PROVIDER_TYPES } from './ProviderTypes';

export const networkListInfoReserved: iNetworkInfo[] = [
  {
    id: 1,
    isInUse: true,
    name: 'Polygon',
    symbol: 'POL',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '137',
    rpcUrls: [
      'https://polygon-rpc.com/',
      'https://rpc-mainnet.maticvigil.com/',
    ],
    img: 'polygon.svg',
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    contractAddress: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    cryptos:[
      {
        name: 'USDT',
        symbol: 'USDT',
        decimals: '6',
        contractAddress:'0xc2132D05D31c914a87C6611C10748AEb04B58e8F'
      }
    ],
    blockExplorerUrls: ['https://polygonscan.com/'],
  },
  {
    id: 2,
    isInUse: true,
    name: 'CELO',
    symbol: 'CEL',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '42220',
    rpcUrls: ['https://forno.celo.org'],
    img: 'celo.svg',
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18,
    },
    blockExplorerUrls: ['https://celoscan.io/'],
  },
  {
    id: 3,
    isInUse: true,
    name: 'Arbitrum One',
    symbol: 'ARB',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '42161',
    rpcUrls: ['https://arb1.arbitrum.io/rpc'],
    img: 'arbitrum.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    blockExplorerUrls: ['https://arbiscan.io/'],
  },
  {
    id: 4,
    isInUse: true,
    name: 'Base',
    symbol: 'Base',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '8453',
    rpcUrls: ['https://base.llamarpc.com'],
    img: 'base.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    blockExplorerUrls: ['https://basescan.org'],
  },
  {
    id: 5,
    isInUse: true,
    name: 'Scroll',
    symbol: 'Scroll',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '534352',
    rpcUrls: ['https://rpc.scroll.io'],
    img: 'scroll.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    blockExplorerUrls: ['https://scrollscan.com'],
  },
  {
    id: 6,
    isInUse: true,
    name: 'Zksync',
    symbol: 'Zksync',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '324',
    rpcUrls: ['https://zksync-era.blockpi.network/v1/rpc/public'],
    img: 'zksync.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    blockExplorerUrls: ['https://explorer.zksync.io'],
  },
  {
    id: 7,
    isInUse: true,
    name: 'Gnosis',
    symbol: 'Gnosis',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '100',
    rpcUrls: [
      'https://rpc.gnosischain.com/',
      'https://rpc.xdaichain.com/',
      'https://dai.poa.network/',
    ],
    img: 'gnosis.svg',
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'XDAI',
      decimals: 18,
    },
    blockExplorerUrls: ['https://gnosisscan.io'],
  },
  {
    id: 8,
    isInUse: true,
    name: 'Mantle',
    symbol: 'Mantle',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '5000',
    rpcUrls: ['https://mantle.publicnode.com'],
    img: 'mantle.svg',
    nativeCurrency: {
      name: 'MNT',
      symbol: 'MNT',
      decimals: 18,
    },
    blockExplorerUrls: ['https://explorer.mantle.xyz'],
  },
  {
    id: 9,
    isInUse: true,
    name: 'XDC Network',
    symbol: 'XDC',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '50',
    rpcUrls: ['https://rpc.xdcrpc.com'],
    img: 'xdc.svg',
    nativeCurrency: {
      name: 'XDC',
      symbol: 'XDC',
      decimals: 18,
    },
    blockExplorerUrls: ['https://xdcscan.io'],
  },
  {
    id: 10,
    isInUse: true,
    name: 'Linea',
    symbol: 'Linea',
    wallets: [PROVIDER_TYPES.METAMASK, PROVIDER_TYPES.WALLET_CONNECT],
    chainType: CHAIN_TYPE.EVM,
    chainId: '59144',
    rpcUrls: ['https://linea.blockpi.network/v1/rpc/public'],
    img: 'linea.svg',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    blockExplorerUrls: ['https://lineascan.build'],
  },
];
